<a href="https://colab.research.google.com/github/boshuaiYu/Deeplearning_pytorch/blob/main/Chapter_2.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

第二章 数据操作

In [ ]:
import torch
print(torch.__version__)

1.12.1+cu113


In [ ]:
x = torch.arange(12)
x, x.shape, x.size(), x.numel()

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 torch.Size([12]),
 torch.Size([12]),
 12)

1. 在numpy中， shape得到了数组的形状，size统计了数组总共的大小，而size也可以在某个轴上进行统计，这样也就达到了得到数组某个轴上形状的目的。
2. 在torch模块，tensor.size()和tensor.shape都会返回Tensor的形状大小，注意size带()
3. torch中，得到张量元素总数的方法是x.numel()


In [ ]:
X = x.reshape(3,4) # reshape只改变张量的形状，并不改变其元素值
X = x.reshape(-1,4)
X = x.reshape(3,-1)
# 以上三种都是一样的

In [ ]:
# 创建全0，全1，随机分布的初始化张量
torch.zeros((2,3,4)) , torch.ones((2,3,4)), torch.randn(2,3,4)

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]), tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]), tensor([[[-0.0967,  1.2059, -1.3103,  1.3358],
          [-0.5490, -1.0875, -0.5596, -0.3418],
          [-0.6110, -1.1053,  0.5342,  0.1262]],
 
         [[ 0.4062,  0.1698, -1.2688,  0.0349],
          [-1.0562, -1.2842,  0.6903,  1.0508],
          [ 0.9717,  0.0163,  0.2937, -2.6779]]]))

可以通过提供包含数值的Python列表（或嵌套列表），来为所需张量中的每个元素赋予确定值。 在这里，最外层的列表对应于轴0，内层的列表对应于轴1

In [ ]:
A = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
A.shape, A.size(0), A.size(1)

(torch.Size([3, 4]), 3, 4)

In [ ]:
A = torch.tensor([[[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]])
A.shape, A.size(0), A.size(1), A.size(2)

(torch.Size([1, 3, 4]), 1, 3, 4)

把多个张量连结（concatenate）在一起， 把它们端对端地叠起来形成一个更大的张量。 我们只需要提供张量列表，并给出沿哪个轴连结。下面分别演示了当我们沿行（轴-0，形状的第一个元素） 和按列（轴-1，形状的第二个元素）

In [ ]:
X = torch.arange(12,dtype=torch.float32).reshape(3,4)  
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])  
A = torch.cat((X,Y), dim=0)
B = torch.cat((X,Y), dim=1) 
X.shape, Y.shape, A, B, A.shape, B.shape                                                                                                                         

(torch.Size([3, 4]), torch.Size([3, 4]), tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]), tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]), torch.Size([6, 4]), torch.Size([3, 8]))

广播机制：形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作。 这种机制的工作方式如下：首先，通过适当复制元素来扩展一个或两个数组， 以便在转换之后，两个张量具有相同的形状。 其次，对生成的数组执行按元素操作

In [ ]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b, a+b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]), tensor([[0, 1],
         [1, 2],
         [2, 3]]))

1. 运行一些操作可能会导致为新结果分配内存。 例如，如果我们用Y = X + Y，我们将取消引用Y指向的张量，而是指向新分配的内存处的张量,增加了没必要的内存
2. 可以使用切片表示法将操作的结果分配给先前分配的数组，例如Y[:] = <expression>。 为了说明这一点，我们首先创建一个新的矩阵Z，其形状与另一个Y相同， 使用zeros_like来分配一个全的块
3. 如果在后续计算中没有重复使用X， 我们也可以使用X[:] = X + Y或X += Y来减少操作的内存开销


In [ ]:
X = torch.arange(3).reshape((3, 1))
Y = torch.arange(3).reshape((3, 1))
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))
before = id(X)
X += Y
id(X) == before


id(Z): 140512118462416
id(Z): 140512118462416


True

深度学习框架定义的张量转换为NumPy张量（ndarray）很容易，反之也同样容易。 torch张量和numpy数组将共享它们的底层内存，就地操作更改一个张量也会同时更改另一个张量

In [ ]:
X = torch.tensor([1.0, 2, 4, 8])
print(id(X))
A = X.numpy()
print(id(A))
X.add_(1), A

140512118146256
140512118147184


(tensor([2., 3., 5., 9.]), array([2., 3., 5., 9.], dtype=float32))

把numpy转成tensor a = numpy.ones(5)，
1. b = torch.tensor(a) 相当于创建一个新tensor，不会共享内存
2. b = torch.from_numpy(a) 相当于从获取numpy中的值，会共享内存

所以numpy和from_numpy会共享内存，torch.tensor不会共享内存

In [ ]:
import numpy as np
a = np.ones(5)
print(id(a))
b1 = torch.tensor(a) # 不会共享内存
b2 = torch.from_numpy(a) # 会共享内存
print(id(b1))
print(id(b2))
a += 1
b1, b2

140512117830160
140512118206000
140512118203600


(tensor([1., 1., 1., 1., 1.], dtype=torch.float64),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))